### ISSUE TITLE
Security problems: Debug mode made it into production. 

### ISSUE THREAD

**Issue by Brainiarc7** [allwinner-zh/linux-3.4-sunxi#16]
See this for more details:

http://www.theregister.co.uk/2016/05/09/allwinners_allloser_custom_kernel_has_a_nasty_root_backdoor/

**Comment by allwinner-zh** [comment]
Have removed it. We will let our clients update it.

**Comment by MatthiasWinkelmann** [comment]
Where exactly did you remove it? It's still alive and well in this repository, there's also no information to be found about it unless you already know about it.

**Comment by ThomasKaiser** [comment]
Did you realize that there is more than one branch in your repo? https://github.com/allwinner-zh/linux-3.4-sunxi/blob/A83T/arch/arm/mach-sunxi/sunxi-debug.c

**Comment by Brainiarc7** [comment]
Seriously guys,

Clean up your act.
