### ISSUE TITLE
No source for /arch/arm/mach-sunxi/pm/standby/gen_check_code

### ISSUE THREAD

**Issue by wingrime** [allwinner-zh/linux-3.4-sunxi#4]
Binary only

**Comment by allwinner-zh** [comment]
gen_check_code is a tool which is running on host PC, it should be not an issue, and there is no open source for it.

**Comment by hno** [comment]
It is a problem. Not a huge one, but still a problem. One solution is to remove the tool from kernel sources and distribute separately.

**Comment by allwinner-zh** [comment]
I have removed it, and placed it to the sunxi-tools repository.
