### ISSUE TITLE
No source for arisc so-core blobs

### ISSUE THREAD

**Issue by wingrime** [allwinner-zh/linux-3.4-sunxi#5]
/drivers/arisc/binary/*
So-core have no any sources and documents.

**Comment by allwinner-zh** [comment]
/drivers/arisc/binary/* is firmware for co-processor, and there is no opensource for it.

**Comment by hno** [comment]
Should probably be reworked to use firmware loading interface instead of embedding the firmware into the kernel.

**Comment by allwinner-zh** [comment]
The format of SCP firmware has been changed from binary to text source.
